### ISSUE TITLE
Create a docker Image of the water quality module

### ISSUE THREAD

**Issue by jfmartinez4** [ciesin-geospatial/TOPSTSCHOOL-air-quality#16]
- Review any module 2 lessons with python code.
- Make a list of all python packages needed to complete the modules.
Done: create pull request to Update the Module 2 repo's DOCKERFILE to include pip install lines for the missing packages. (The existing document has some already so the format can just be extended for missing packages.)

Docker file to update: https://github.com/ciesin-geospatial/TOPSTSCHOOL-air-quality/blob/main/dockerfile
Module repo: https://github.com/ciesin-geospatial/TOPSTSCHOOL-air-quality

**Comment by jfmartinez4** [comment]
- Went through module 2 and added from lesson 2 and 4)
- Create a docker image. Use this as reference: https://github.com/ciesin-geospatial/TOPSTSCHOOL-water/blob/main/Dockerfile-dev
- Pull Request tutorials: https://www.youtube.com/watch?v=LM779rqUlvE  https://www.youtube.com/watch?v=XgxoGnMrPLs

**Comment by jfmartinez4** [comment]
@JR224-jpg the air qualirty module is on Python, so focus the docker image in that. Thanks!!

**Comment by jfmartinez4** [comment]
@JR224-jpg I was wondering if you could provide an update on this task. Thank you!

**Comment by JR224-jpg** [comment]
- I’ve been working on the Docker image, particularly the Dockerfile that will be used to build it. I believe it is nearly done. 
- I’ve compiled a list of dependencies required to run Python, as it was specified that the environment will be Python-based.
- I’ve emailed you the files through my school email.
- I’ve also responded to your previous email.

**Comment by jfmartinez4** [comment]
Github Pull: 
https://www.youtube.com/watch?v=LM779rqUlvE
https://www.youtube.com/watch?v=XgxoGnMrPLs


From Josh on Docker files:

1. Review any module 2 lessons with python code.

2. Make a list of all python packages needed to complete the modules.

> 1. These should all be listed towards the top (at least in mine)

3. Update the Module 2 repo's DOCKERFILE to include pip install lines for the missing packages.

> 1. The existing document has some already so the format can just be extended for missing packages.

Testing
It would help to test any python lessons inside of the container, however, this requires 2 additional steps we normally achieve via 2i2c.

1. Use an ADD or COPY command in the docker build to add the .qmd lessons
2. Use an ADD or COPY command in the docker build to add any files for the lessons that aren't acquired via api (e.g. SVI in my ej lesson)

Once that is finished.

1. Build the container on a local system
2. Use VS code to port into the system, or any other method you may like.
3. Run the lessons to make sure they work 

Once it's verified I'll prepare it for 2i2c and register the image to [quay.io](http://quay.io/)

Let me know if more clarification is needed.

**Comment by joshbrinks** [comment]
Ah right, :latest is best. I was originally using FROM ubuntu:20.04 because I was testing on my PC, but commented it out seeing if rocker/binder:latest would work, because I suspect 2i2c would want us to use rocker/binder even though the image will be a little bigger than starting from scratch with Ubuntu 20.04 or 22.04.

As far as ADD . /AIR_QUALITY (make sure there is a space between the period and forward slash otherwise it won't copy anything).

Once you're inside the container with VS Code you'll want to find the /AIR_QUALITY folder and then start trying to run the lessons. It will be in the root directory as listed, but you can see the default directory VS Code is showing when you port in and then rebuild the container with:

ADD . /<DEFAULT VS CODE DIRECTORY>/AIR_QUALITY

So it will be right there when you port in.

**Comment by jfmartinez4** [comment]
@JR224-jpg Please send any final files, or please let me know where you uploaded them..
Thank you
